import { QuantitativeLayout } from "../quantitative/quantitative_layout.slint";
import { CorrelationRow, ReturnRowData, RsiData, CoinData, MaData, CryptoData, DominanceChartData, EtfFlowData, CryptoMarketCapData } from "../../data_type.slint";
import { SectorRangeSnapshot } from "../quantitative/quantitative_price_trade_heatmap.slint";

export component QuantitativeAnalysis inherits Rectangle {
    in-out property <[string]> selected_tags: ["ACB", "VPB"];
    in property <[CorrelationRow]> correlation_rows: [];
    in property <[string]> correlation_columns: [];
    in property <[RsiData]> rsi_list;
    in property <[CoinData]> coin_list;
    in property <[MaData]> ma_list;
    in property <[CoinData]> ma_coin_list;
    in property <[CryptoData]> crypto_list; 
    in property <float> rsi_overbought_pct: 0.0;
    in property <float> rsi_oversold_pct: 0.0;
    in property <float> ma_above_pct: 0.0;
    in property <float> ma_below_pct: 0.0;
    in property <DominanceChartData> dominance_data;
    in property <[CoinData]> crypto_coin_list; 
    in property <EtfFlowData> etf_flow_data;
    in property <CryptoMarketCapData> market_cap_data;
    in-out property <[SectorRangeSnapshot]> sector_ranges;

    callback on_add_tag(string);
    callback on_remove_tag(int);
    callback calculateCorrelation(string);
    callback sort_rsi14();
    callback sort_ma50();
    //return matrix data
    in property <[ReturnRowData]> return_row_data: [];
    callback getReturnMatrix(string, string, string);
    QuantitativeLayout {
        width: 100%;
        height: 100%;
        //binding selected tags
        selected_tags <=> root.selected_tags;
        correlation_rows: root.correlation_rows;
        correlation_columns: root.correlation_columns;
        return_row_data: root.return_row_data;
        on_add_tag(tag) => {
            root.on_add_tag(tag);
        }   
        on_remove_tag(index) => {
            root.on_remove_tag(index);
        }
        calculateCorrelation(type) => {
            root.calculateCorrelation(type);    
        }
        getReturnMatrix(period, group, month) => {
            root.getReturnMatrix(period, group, month);
        }

        rsi_list: root.rsi_list;
        coin_list: root.coin_list;
        ma_list: root.ma_list;
        ma_coin_list: root.ma_coin_list;
        rsi_overbought_pct: root.rsi_overbought_pct;
        rsi_oversold_pct: root.rsi_oversold_pct;
        ma_above_pct: root.ma_above_pct;
        ma_below_pct: root.ma_below_pct;
        sort_rsi14 => {root.sort_rsi14();}
        sort_ma50 => {root.sort_ma50();}
        crypto_list: root.crypto_list;
        dominance_data: root.dominance_data;
        crypto_coin_list: root.crypto_coin_list;
        etf_flow_data: root.etf_flow_data;
        market_cap_data: root.market_cap_data;
        sector_ranges <=> root.sector_ranges;
    }} 